name: Flutter CI

on: push

jobs:
  build-and-release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.0.5'
          architecture: x64
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Palettly-${{github.ref_name}}.zip
          directory: build/macos/Build/Products/Release
      - name: macOS Relase
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/macos/Build/Products/Release/Palettly-${{github.ref_name}}.zip"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}    
